theorem mul_left_cancel (a b c : mynat) (ha : a ≠ 0) : a * b = a * c → b = c :=
begin
induction c with d hd generalizing b,
rw mul_zero,
rw mul_eq_zero_iff,
intro h,
cases h,
exfalso,
exact ha h,
exact h,
intro h,
cases b,
rw mul_zero at h,
symmetry at h,
rw mul_eq_zero_iff at h,
cases h,
exfalso,
exact ha h,
symmetry at h,
exact h,
rw succ_eq_succ_iff,
apply hd,
rw mul_succ at h,
rw mul_succ at h,
apply add_right_cancel _ a _,
exact h,
end
